### ISSUE TITLE
Westend faucet: web3.foundation Matrix accounts whitelisted but can't do > 1 WND drips

### ISSUE THREAD

**Issue by laboon** [paritytech/substrate-matrix-faucet#115]
This is on the Matrix Westend faucet.

You can see that it worked for Chevdor (who has a parity.io account) but not for my web3.foundation account, which should also be whitelisted.

```
Bill | W3F
!drip 5EJB3zyidPPnT5bw5RgQ6EKqc6ZvrLkUjYPHStGHZArPUMUH 2000
faucet
Sent @bill:web3.foundation 1 WNDs. Extrinsic hash: 0x039e29809b1bbd7f193e707ffddc973f7e71cd9aaacbd432513a9a23e8a42a23
Bill | W3F
!balance
faucet
The faucet has 48244.067049875484 WNDs remaining.
Will / Chevdor
!help
faucet
The following commands are supported:
!balance - Get the faucet's balance.
!drip <Address> - Send WNDs to <Address>.
!help - Print this message
Will / Chevdor
!drip 5EJB3zyidPPnT5bw5RgQ6EKqc6ZvrLkUjYPHStGHZArPUMUH 2
faucet
Sent @chevdor:matrix.parity.io 2 WNDs. Extrinsic hash: 0xbbcb65410b2d20e57444f65504cfc216126fc4bebec499c4074849d137c38394
```

**Comment by chevdor** [comment]
Unfortunately, the Loki logs are not available right now so I could not get more details.
@laboon's account had less than 100 WND so the issue is **not** the balance cap (which should anyway work as well for whitelisted accounts).

I also followed up sending @laboon 2000 WND which worked fine as well.
