### ISSUE TITLE
Separate the needed env for the bot and the server...

### ISSUE THREAD

**Issue by Tbaut** [paritytech/substrate-matrix-faucet#19]
.. since those will end up being 2 diff docker
- don't use the same `verifyEnvVariables`
- use a `PORT` variable for thee server (which should match with the port defined in `BACKEND_URL`

**Comment by fevo1971** [comment]
true, defining only the variables in the (server or bot) container that are relevant for it's functionality instead of defining all the envvars in every container is a good idea.


regarding the hardcoded port (5555) in the server, either introduce a new environment variable `PORT` or `SERVER_PORT` or 
deduct from the existing `BACKEND_URL` variable `PORT=BACKEND_URL.split(":",2)`maybe?

**Comment by Tbaut** [comment]
closed by #20
